version: "3"

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: 127.0.0.1

  my-habit:
    image: my_habit:latest
    links:
      - mysql
    ports:
      - 80:8085
